name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - dev
      - test
      - prod

jobs:
  build-and-push:
    runs-on: self-hosted
    if: github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod' || github.ref_name == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS ECR credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: dennis-test-ga
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            IMAGE_TAG="latest"
          else
            IMAGE_TAG="${{ github.ref_name }}"
          fi
          docker build . -t $REGISTRY/dennis-test-ga:$IMAGE_TAG
          docker push $REGISTRY/dennis-test-ga:$IMAGE_TAG
